# PyTorch Basic
- https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

# 1. Tensors

In [6]:
from __future__ import print_function
import torch

In [7]:
# initiailzation 되지 않은 5 x 3행렬 생성
x = torch.empty(5, 3)
print(x)

tensor([[8.4490e-39, 1.1020e-38, 1.0469e-38],
        [9.6429e-39, 9.2755e-39, 9.9184e-39],
        [9.0000e-39, 9.5510e-39, 1.0653e-38],
        [8.4490e-39, 9.9184e-39, 9.2755e-39],
        [1.0653e-38, 1.0286e-38, 1.6956e-43]])


In [8]:
# random initialization 된 행렬
x = torch.randn(5,3)
print(x)

tensor([[-0.3639, -0.7146,  0.6279],
        [ 0.2144, -0.3045, -0.4121],
        [-0.2039,  0.5263, -1.0069],
        [-0.1056, -0.1096,  0.5159],
        [ 0.0710, -0.5606, -0.3361]])


In [9]:
# dtype이 long이고 0으로 채워진 행렬
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
# 데이터로부터 tensor를 직접 생성
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


# 2. Autograd

- autograd 패키지는 Tensor의 모든 연산에 대해 자동 미분을 제공

## 2.1. Tensor
- requires_grad=True로 설정하면 해당 tensor의 모든 연산을 추적함.
  - .backward()를 사용해 모든 gradient를 자동 계산. 이 Tensor의 gradients는 .grad 속성에 누적됨
  - .grad_fn : 연산의 결과로 나온 Tensor가 가지는 속성으로, 자기 자신을 생성한 Function을 참조.
  - .detach() : 기록 추적 중단 
  
- with torch.no_grad(): 모델 평가시
  

In [13]:
import torch
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [14]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


y는 연산 결과로 나온 것이므로 grad_fn을 갖는다.

In [16]:
print(y.grad_fn)

In [17]:
z = y * y + 3
out = z.mean()

print(z, out)

tensor([[12., 12.],
        [12., 12.]], grad_fn=<AddBackward0>) tensor(12., grad_fn=<MeanBackward0>)


- 메서드 뒤에 \_가 붙으면 inplace 옵션으로 실행, 값을 바꿔치기한다.  
ex) .required_grad_(...)

In [18]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## 3. Gradient

In [19]:
out.backward()

gradient d(out)/dx 를 출력

In [20]:
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [22]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ 685.8822, -867.7253, 1122.1738], grad_fn=<MulBackward0>)


with torch.no_grad(): 를 이용하여 autograd가 .requires_grad=True인 Tensor들의 연산 기록을 추적하는 것을 멈출 수 있다.

In [24]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
